In [1]:
import numpy as np

Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [4]:
import numpy as np

a = np.array([1, 2, 3, 4, 5], dtype=float)

print(a)

[1. 2. 3. 4. 5.]


Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [7]:
import numpy as np

m = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]], dtype=int)

print(m)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [10]:
import numpy as np
b = np.zeros((3, 3), dtype="u4")
print(b)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [11]:
import numpy as np

matrix = np.random.randint(1, 11, size=(5, 5))

print(matrix)

[[10  6  7  3  2]
 [ 7  1 10 10  1]
 [ 7  4  4  8  2]
 [10  8  1  2  3]
 [ 1  7 10  3  2]]


Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [13]:
import numpy as np

b = np.random.uniform(0, 1, size=(4, 4))

print(b)

[[0.13167128 0.90294881 0.003589   0.18627814]
 [0.08167162 0.57147063 0.99299826 0.66659517]
 [0.09224825 0.91877094 0.202445   0.75945288]
 [0.3604994  0.16922713 0.79785081 0.83538959]]


Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [16]:
import numpy as np

matrix1 = np.random.randint(1, 11, size=(5, 1))
matrix2 = np.random.randint(1, 11, size=(5, 1))


print(matrix1+matrix2)
print(matrix1-matrix2)
print(matrix1*matrix2)

[[ 3]
 [12]
 [15]
 [ 4]
 [14]]
[[ 1]
 [-4]
 [ 3]
 [ 2]
 [ 6]]
[[ 2]
 [32]
 [54]
 [ 3]
 [40]]


Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [17]:
import numpy as np

matrix3 = np.random.randint(1, 11, size=(7,7))
matrix4 = np.random.randint(1, 11, size=(7,7))
print(np.dot(matrix3, matrix4))  

[[193 245 251 210 248 213 136]
 [255 320 306 248 320 243 185]
 [229 295 256 225 297 202 181]
 [238 289 249 220 289 234 140]
 [176 239 253 217 248 171 171]
 [215 245 274 226 274 227 166]
 [181 224 287 259 269 216 191]]


Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [1]:
import numpy as np

matrix5 = np.random.randint(1, 11, size=(2,2))
matrix6 = np.random.randint(1, 11, size=(2,3))
print(np.dot(matrix5, matrix6))  

[[170 130  82]
 [171 135  81]]


Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [4]:
import numpy as np

matrix7 = np.random.randint(1, 11, size=(3,3))
print(matrix7)


matrix8 = np.linalg.inv(matrix7)


print(matrix8)

[[ 9  8 10]
 [ 7 10 10]
 [ 5  1  1]]
[[ 0.         -0.02325581  0.23255814]
 [-0.5         0.47674419  0.23255814]
 [ 0.5        -0.36046512 -0.39534884]]


Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [5]:
import numpy as np



matrix9 = np.random.uniform(0, 1, size=(4, 4))

print(matrix9)

matrix10 = matrix9.T
print(matrix10)

[[0.22403134 0.99372839 0.75908799 0.76631324]
 [0.35763544 0.26812855 0.60783861 0.35204685]
 [0.36730252 0.26425085 0.18594563 0.59937275]
 [0.57326798 0.15248139 0.40736714 0.74006323]]
[[0.22403134 0.35763544 0.36730252 0.57326798]
 [0.99372839 0.26812855 0.26425085 0.15248139]
 [0.75908799 0.60783861 0.18594563 0.40736714]
 [0.76631324 0.35204685 0.59937275 0.74006323]]


Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [9]:
import numpy as np

matrix11 = np.random.randint(1, 11, size=(3,4))
print(matrix11)
matrix12 = np.random.randint(1, 11, size=4)
print(matrix12)


print(np.dot(matrix11, matrix12))  

[[ 2 10  3  5]
 [ 6  2 10  3]
 [ 6  5  8  6]]
[9 2 4 5]
[ 75 113 126]


Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [12]:
import numpy as np
matrix13 = np.random.uniform(0, 1, size=(2, 3))
print(matrix13)
matrix14 = np.random.random(size=3)
print(matrix14)
print(np.dot(matrix13, matrix14)) 

[[0.29821771 0.10587322 0.70680918]
 [0.65642232 0.49549352 0.21291906]]
[0.25581349 0.77094564 0.16336783]
[0.27338049 0.58470437]


Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [13]:
import numpy as np

matrix15 = np.random.randint(1, 11, size=(2,2))
matrix16 = np.random.randint(1, 11, size=(2,2))



multiply = np.multiply(matrix15, matrix16)

print(multiply)

[[ 3  8]
 [35 24]]


Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [14]:
import numpy as np

matrix17 = np.random.randint(1, 11, size=(2,2))
matrix18 = np.random.randint(1, 11, size=(2,2))

multuply_result= np.dot(matrix17, matrix18)
print(multuply_result)

[[39 19]
 [52 22]]


Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [15]:
import numpy as np

matrix19 = np.random.randint(1, 101, size=(5,5))

print(matrix19.sum())

1194


Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [17]:
import numpy as np

matrix20 = np.random.randint(1, 11, size=(4,4))
matrix21 = np.random.randint(1, 11, size=(4,4))

difference = matrix20 - matrix21
print(difference)

[[ 1  4 -3 -1]
 [ 1 -2 -1 -1]
 [-4 -1  3 -1]
 [ 1  4  1  7]]


Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [21]:

import numpy as np

matrix22 = np.random.uniform(0, 1, size=(3, 3))

sumline1 = np.sum(matrix22 , axis=1)

print (sumline1)


[1.12864066 2.14539985 1.95834869]


Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [26]:
import numpy as np

matrix25 = np.random.randint(1,50, size=(3,4))
print(matrix25)
matrix_power = np.power(matrix25,2)
print(matrix_power)

[[ 4  6 10 10]
 [20 36 31 20]
 [36 14 16 46]]
[[  16   36  100  100]
 [ 400 1296  961  400]
 [1296  196  256 2116]]


Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.


In [23]:
import numpy as np

matrix23 = np.random.randint(1, 50 , size=(3,4))
print(matrix23)
sq_root = np.sqrt(matrix23)





print(sq_root)

[[22  9 31 39]
 [ 1  9  2  5]
 [44 44 16 11]]
[[4.69041576 3.         5.56776436 6.244998  ]
 [1.         3.         1.41421356 2.23606798]
 [6.63324958 6.63324958 4.         3.31662479]]
